spring.application.name=flashcard-web

spring.datasource.url=jdbc:postgresql://localhost:5432/flashcard_db
spring.datasource.username=postgres
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
google.client-id=591018459960-sbvbs143it9eoi2hl1k9ca0ms8gsvfln.apps.googleusercontent.com